<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Company;
use Carbon\Carbon;

class DocumentController extends Controller
{
    public function index(\Illuminate\Http\Request $request)
    {
        $user = auth()->user();
        if (in_array($user->role, ['superadmin', 'admin'])) {
            $companies = Company::all();
            $companyId = $request->query('company_id');
            $company = $companyId ? Company::find($companyId) : $companies->first();
            $employees = User::where('company_id', $company->id ?? null)->where('role', 'employee')->get();
            $allEmployees = User::where('role', 'employee')->get();
            return view('admin.documents.index', compact('company', 'employees', 'companies', 'allEmployees'));
        } else {
            $company = $user->company;
            $employees = User::where('company_id', $user->company_id)->where('role', 'employee')->get();
            $companies = collect([$company]);
            $allEmployees = $employees;
            return view('admin.documents.index', compact('company', 'employees', 'companies', 'allEmployees'));
        }
    }

    public function generate(Request $request)
    {
        $request->validate([
            'employee_id'              => 'required|exists:users,id',
            'documents'                => 'required|array|min:1',
            'designation'              => 'required|string|max:255',
            'department'               => 'required|string|max:255',
            'employment_type'          => 'required|in:full-time,part-time,contract,intern',
            'start_date'               => 'required|date',
            'reporting_manager'        => 'required|string|max:255',
            'work_location'            => 'required|string|max:255',
            'base_salary'              => 'required|numeric|min:0',
            'currency'                 => 'required|string|max:10',
            'pay_frequency'            => 'required|in:monthly,bi-monthly,weekly',
            'bonus_structure'          => 'nullable|string|max:500',
            'probation_period_months'  => 'required|integer|min:0',
            'notice_period_days'       => 'required|integer|min:0',
            'non_compete_duration_months' => 'required|integer|min:0',
            'non_compete_geographic_scope' => 'required|string|max:255',
            'confidentiality_duration_years' => 'required|integer|min:1',
            'jurisdiction'             => 'required|string|max:255',
            'signatory_name'           => 'required|string|max:255',
            'signatory_title'          => 'required|string|max:255',
            'leave_types'              => 'nullable|array',
        ]);

        $employee  = User::findOrFail($request->employee_id);
        
        // Update employee profile so future documents generated by them will reflect these changes
        $employee->update([
            'department'                     => $request->department,
            'position'                       => $request->designation,
            'salary'                         => $request->base_salary,
            'employment_type'                => $request->employment_type,
            'reporting_manager'              => $request->reporting_manager,
            'work_location'                  => $request->work_location,
            'currency'                       => $request->currency,
            'pay_frequency'                  => $request->pay_frequency,
            'bonus_structure'                => $request->bonus_structure,
            'probation_period_months'        => $request->probation_period_months,
            'notice_period_days'             => $request->notice_period_days,
            'non_compete_duration_months'    => $request->non_compete_duration_months,
            'confidentiality_duration_years' => $request->confidentiality_duration_years,
            'non_compete_geographic_scope'   => $request->non_compete_geographic_scope,
        ]);
        $company   = $employee->company ?? auth()->user()->company;
        $today     = Carbon::today()->format('Y-m-d');

        $data = [
            'company_name'             => $company->name ?? 'Your Company',
            'company_address'          => $company->address ?? 'Plot 93, Rajendra Park, Sector 105, Gurugram � 122001. Haryana',
            'company_logo'             => $company->logo ? asset('storage/' . $company->logo) : '',
            'signatory_name'           => $request->signatory_name,
            'signatory_title'          => $request->signatory_title,
            'employee_name'            => $employee->name,
            'designation'              => $request->designation,
            'department'               => $request->department,
            'employment_type'          => ucfirst($request->employment_type),
            'start_date'               => Carbon::parse($request->start_date)->format('d F Y'),
            'reporting_manager'        => $request->reporting_manager,
            'work_location'            => $request->work_location,
            'base_salary'              => number_format($request->base_salary, 2),
            'currency'                 => $request->currency,
            'pay_frequency'            => ucfirst($request->pay_frequency),
            'bonus_structure'          => $request->bonus_structure ?: 'As per company policy',
            'probation_period_months'  => $request->probation_period_months,
            'notice_period_days'       => $request->notice_period_days,
            'non_compete_duration_months' => $request->non_compete_duration_months,
            'non_compete_geographic_scope' => $request->non_compete_geographic_scope,
            'confidentiality_duration_years' => $request->confidentiality_duration_years,
            'jurisdiction'             => $request->jurisdiction,
            'generated_date'           => $today,
            'leave_types'              => $request->leave_types ?? [],
        ];

        $documents = [];

        foreach ($request->documents as $type) {
            switch ($type) {
                case 'offer_letter':
                    $documents[] = $this->generateOfferLetter($data);
                    break;
                case 'nda':
                    $documents[] = $this->generateNDA($data);
                    break;
                case 'appointment_letter':
                    $documents[] = $this->generateAppointmentLetter($data);
                    break;
                case 'employment_contract':
                    $documents[] = $this->generateEmploymentContract($data);
                    break;
                case 'non_compete':
                    $documents[] = $this->generateNonCompete($data);
                    break;
                case 'leave_policy':
                    $documents[] = $this->generateLeavePolicy($data);
                    break;
            }
        }

        return view('admin.documents.preview', compact('documents', 'data'));
    }

    // ─── OFFER LETTER ────────────────────────────────────────────────────────────
    private function generateOfferLetter(array $d): array
    {
        $logoHtml = $d['company_logo'] ? '<img src="' . $d['company_logo'] . '" alt="Logo" style="height: 90px; width: auto; max-width: 180px; object-fit: contain;">' : '';
        $d = array_merge([
            'company_name' => 'Your Company',
            'company_address' => 'Plot 93, Rajendra Park, Sector 105, Gurugram � 122001. Haryana',
            'employee_address' => 'Employee Address',
            'benefits_description' => 'Standard company benefits as per policy',
            'dispute_negotiation_days' => 30,
            'dispute_resolution_mechanism' => 'Binding Arbitration',
            'competitor_1' => 'Competitor A',
            'sector_1' => 'Technology',
            'competitor_2' => 'Competitor B',
            'sector_2' => 'Software',
            'competitor_3' => 'Competitor C',
            'sector_3' => 'IT Services',
            'leave_type_name' => 'Annual Leave',
            'days_per_year' => 20,
            'remarks' => 'Subject to approval',
            'annual_leave_days' => 20,
            'sick_leave_days' => 10,
            'casual_leave_days' => 5,
            'accrual_method' => 'monthly',
            'leave_application_notice_days' => 14,
            'sick_leave_doc_threshold' => 3,
            'max_carry_forward_days' => 5,
            'employee_work_location' => 'Office',
            'max_unpaid_leave_days' => 30,
            'maternity_leave_days' => 12,
            'paternity_leave_days' => 5,
            'bereavement_leave_days' => 3,
            'policy_review_frequency' => 'annually',
            'bonus_structure' => 'As per company policy',
        ], $d);
        $content = <<<MD
<div style="text-align: right; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px;">
    {$logoHtml}
    <p style="margin: 5px 0 0; font-size: 12px; font-weight: bold;">{$d['company_address']}</p>
</div>

**Date:** {$d['generated_date']}  
**Name:** {$d['employee_name']}  
**Address:** {$d['company_address']}  
**Subject:** Offer of Employment as {$d['designation']}  

Dear {$d['employee_name']},

We are pleased to offer you the position of {$d['designation']} at {$d['company_name']}. Your passion for technology, commitment to learning, and problem-solving approach have impressed us, and we believe you will be a valuable asset to our team.

Please find below the key terms and conditions of your employment:
**Designation:** {$d['designation']}  
**Department:** {$d['department']}  
**Employment Type:** {$d['employment_type']}  
**Location:** {$d['work_location']}  
**Joining Date:** {$d['start_date']}  
**Initial Salary:** {$d['currency']} {$d['base_salary']} per month  

Your salary will be reviewed based on your performance, dedication, and contribution to the company. As your performance improves, your remuneration will be revised accordingly.

**Roles & Responsibilities:**
You will be part of our core development team and contribute to the design, development, and maintenance of our software solutions. Your responsibilities will include:
* Developing and maintaining both frontend and backend systems
* Writing clean, efficient, and scalable code
* Participating in daily stand-up meetings and sprint planning
* Collaborating with cross-functional teams
* Debugging, testing, and optimizing applications
* Supporting ongoing projects to meet deadlines

We expect you to maintain high standards of performance, show initiative, and contribute positively to our work culture.

**Terms & Conditions:**
1. **Probation Period:** A probation period of {$d['probation_period_months']} months applies, during which your performance and compatibility with the team will be assessed.
2. **Confidentiality:** You must maintain strict confidentiality of all company-related information, both during and after your employment.
3. **Termination of Employment:** Violation of company policies, underperformance, or any unethical conduct may lead to immediate termination.
4. **Notice Period:** A notice period of {$d['notice_period_days']} days is required in case of resignation. Failure to provide notice may result in forfeiture of benefits.
5. **Performance Reviews:** Regular reviews will be conducted to assess your progress. Increments and growth opportunities will be based on performance and company requirements.
6. **Compliance with Company Policies:** Adherence to all policies related to behaviour, attendance, and dress code is mandatory.
7. **Policy Amendments:** The company reserves the right to update or modify any policy, which will be communicated accordingly.
8. **Dispute Resolution:** Any legal disputes shall fall under the jurisdiction of {$d['jurisdiction']}.
9. **Additional Responsibilities:** You may be assigned additional tasks or projects by your manager as per company requirements.

**Acceptance of Offer:**
Please go through this letter thoroughly. If you accept the terms of this employment, sign and return a copy of this letter as your confirmation.

If you have any questions or need further clarification, feel free to contact our HR department at hr@hatbaliya.in.

We are excited to welcome you to **{$d['company_name']}** and look forward to a successful professional journey together.

Warm regards,  
**{$d['signatory_name']}**  
{$d['signatory_title']}  
{$d['company_name']}  
hr@hatbaliya.in  
MD;

        return [
            'type'            => 'offer_letter',
            'title'           => 'Offer Letter — ' . $d['employee_name'],
            'content'         => $content,
            'editable_fields' => [
                'base_salary', 'start_date', 'probation_period_months',
                'notice_period_days', 'work_location', 'jurisdiction'
            ],
            'version'         => 'v1.0',
            'generated_date'  => $d['generated_date'],
        ];
    }

    // ─── NDA ─────────────────────────────────────────────────────────────────────
    private function generateNDA(array $d): array
    {
        $d = array_merge([
            'company_name' => 'Your Company',
            'company_address' => 'Plot 93, Rajendra Park, Sector 105, Gurugram � 122001. Haryana',
            'employee_address' => 'Employee Address',
            'benefits_description' => 'Standard company benefits as per policy',
            'dispute_negotiation_days' => 30,
            'dispute_resolution_mechanism' => 'Binding Arbitration',
            'competitor_1' => 'Competitor A',
            'sector_1' => 'Technology',
            'competitor_2' => 'Competitor B',
            'sector_2' => 'Software',
            'competitor_3' => 'Competitor C',
            'sector_3' => 'IT Services',
            'leave_type_name' => 'Annual Leave',
            'days_per_year' => 20,
            'remarks' => 'Subject to approval',
            'annual_leave_days' => 20,
            'sick_leave_days' => 10,
            'casual_leave_days' => 5,
            'accrual_method' => 'monthly',
            'leave_application_notice_days' => 14,
            'sick_leave_doc_threshold' => 3,
            'max_carry_forward_days' => 5,
            'employee_work_location' => 'Office',
            'max_unpaid_leave_days' => 30,
            'maternity_leave_days' => 12,
            'paternity_leave_days' => 5,
            'bereavement_leave_days' => 3,
            'policy_review_frequency' => 'annually',
            'bonus_structure' => 'As per company policy',
        ], $d);
        $content = <<<MD
# Non-Disclosure Agreement (NDA)

**{$d['company_name']}**
{$d['company_address']}

**Date:** {$d['generated_date']}

---

This Non-Disclosure Agreement ("Agreement") is entered into as of **{$d['generated_date']}** by and between:

**{$d['company_name']}**, a company duly incorporated and existing under the laws of {$d['jurisdiction']} ("**Company**"), represented by {$d['signatory_name']}, {$d['signatory_title']};

**AND**

**{$d['employee_name']}**, residing at {$d['employee_address']} ("**Employee**"), designated as {$d['designation']} in the {$d['department']} department.

---

## 1. Definition of Confidential Information

"Confidential Information" means any and all non-public information disclosed by the Company to the Employee — whether oral, written, electronic, or in any other form — that:

- Is designated as confidential at the time of disclosure, or
- Reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure.

Confidential Information includes, without limitation: business strategies, financial data, customer and vendor lists, trade secrets, proprietary software, source code, research and development activities, pricing structures, personnel information, and all other information related to the Company's business operations.

## 2. Obligations of Employee

The Employee agrees to:

2.1 Hold all Confidential Information in strict confidence and not disclose it to any third party without the prior written consent of the Company.

2.2 Use Confidential Information solely for the purpose of performing their duties as {$d['designation']} at the Company.

2.3 Limit access to Confidential Information to those who need to know it for legitimate business purposes and who are bound by obligations of confidentiality no less stringent than those contained herein.

2.4 Take all reasonable measures to protect the secrecy of and avoid unauthorized disclosure or use of Confidential Information, including implementing security measures at least as protective as those used to protect their own confidential information.

2.5 Promptly notify the Company in writing upon becoming aware of any unauthorized disclosure or use of Confidential Information.

## 3. Exclusions from Confidentiality

The obligations in Section 2 shall not apply to information that:

3.1 Was already known to the Employee prior to disclosure by the Company, without restriction;

3.2 Is or becomes publicly available through no breach of this Agreement by the Employee;

3.3 Is rightfully received by the Employee from a third party without a duty of confidentiality;

3.4 Is required to be disclosed by applicable law, court order, or government regulation — provided the Employee gives the Company prompt prior written notice and cooperates with the Company in seeking a protective order.

## 4. Duration of Obligation

The Employee's confidentiality obligations under this Agreement shall commence on **{$d['start_date']}** and shall continue:

- Throughout the entire period of employment with the Company; **AND**
- For a period of **{$d['confidentiality_duration_years']} year(s)** following the termination or expiration of employment, for any reason.

## 5. Return of Materials

Upon termination of employment, or at any time upon the Company's request, the Employee shall promptly return or destroy (at the Company's discretion) all materials in their possession or control that contain or embody Confidential Information, including all copies, notes, and summaries thereof, in any medium.

## 6. Remedies for Breach

The Employee acknowledges that any breach or threatened breach of this Agreement may cause the Company irreparable harm for which monetary damages would be an inadequate remedy. Accordingly, the Company shall be entitled, in addition to any other remedies available at law or in equity, to seek injunctive relief to prevent any actual or threatened breach of this Agreement, without the necessity of proving actual damages or posting bond.

## 7. Governing Law

This Agreement shall be governed by and construed in accordance with the laws of **{$d['jurisdiction']}**. Any disputes arising under or relating to this Agreement shall be subject to the exclusive jurisdiction of the competent courts of {$d['jurisdiction']}.

---

**SIGNATURES**

| Party | Signature | Date |
|---|---|---|
| {$d['company_name']} (Authorised Signatory) | ___________________________ | {$d['generated_date']} |
| {$d['signatory_name']}, {$d['signatory_title']} | | |
| {$d['employee_name']} (Employee) | ___________________________ | {$d['generated_date']} |

---

*This document is a template generated for internal HR use and should be reviewed by legal counsel for jurisdiction-specific enforceability.*
MD;

        return [
            'type'            => 'nda',
            'title'           => 'Non-Disclosure Agreement — ' . $d['employee_name'],
            'content'         => $content,
            'editable_fields' => [
                'confidentiality_duration_years', 'employee_address', 'jurisdiction', 'start_date'
            ],
            'version'         => 'v1.0',
            'generated_date'  => $d['generated_date'],
        ];
    }

    // ─── APPOINTMENT LETTER ───────────────────────────────────────────────────────
    private function generateAppointmentLetter(array $d): array
    {
        $d['probation_notice_days'] = $d['probation_notice_days'] ?? 15;
        $d['max_probation_extension_months'] = $d['max_probation_extension_months'] ?? 3;

        $d = array_merge([
            'company_name' => 'Your Company',
            'company_address' => 'Plot 93, Rajendra Park, Sector 105, Gurugram � 122001. Haryana',
            'employee_address' => 'Employee Address',
            'benefits_description' => 'Standard company benefits as per policy',
            'dispute_negotiation_days' => 30,
            'dispute_resolution_mechanism' => 'Binding Arbitration',
            'competitor_1' => 'Competitor A',
            'sector_1' => 'Technology',
            'competitor_2' => 'Competitor B',
            'sector_2' => 'Software',
            'competitor_3' => 'Competitor C',
            'sector_3' => 'IT Services',
            'leave_type_name' => 'Annual Leave',
            'days_per_year' => 20,
            'remarks' => 'Subject to approval',
            'annual_leave_days' => 20,
            'sick_leave_days' => 10,
            'casual_leave_days' => 5,
            'accrual_method' => 'monthly',
            'leave_application_notice_days' => 14,
            'sick_leave_doc_threshold' => 3,
            'max_carry_forward_days' => 5,
            'employee_work_location' => 'Office',
            'max_unpaid_leave_days' => 30,
            'maternity_leave_days' => 12,
            'paternity_leave_days' => 5,
            'bereavement_leave_days' => 3,
            'policy_review_frequency' => 'annually',
            'bonus_structure' => 'As per company policy',
        ], $d);

        $content = <<<MD
# Appointment Letter

**{$d['company_name']}**
{$d['company_address']}

**Date:** {$d['generated_date']}

---

Dear **{$d['employee_name']}**,

We are pleased to confirm your appointment with **{$d['company_name']}** ("the Company") on the terms and conditions set out in this Appointment Letter and the accompanying Employment Contract.

---

## 1. Confirmation of Appointment

The Company hereby appoints **{$d['employee_name']}** to the position of **{$d['designation']}**, effective **{$d['start_date']}**.

## 2. Designation & Department

| Field | Details |
|---|---|
| Designation | {$d['designation']} |
| Department | {$d['department']} |
| Employment Type | {$d['employment_type']} |

## 3. Reporting Structure

You will report to **{$d['reporting_manager']}**. Any change in reporting structure will be communicated in writing by the Company.

## 4. Work Location

Your primary place of work shall be **{$d['work_location']}**. You may be required to travel or work from alternative locations based on business requirements.

## 5. Probation & Confirmation Process

Your appointment is subject to a probationary period of **{$d['probation_period_months']} month(s)** from the date of joining. During this period:

- Your performance will be assessed against pre-defined KPIs and role expectations.
- Either party may terminate employment during probation by providing **{$d['probation_notice_days']} days** written notice.
- Successful completion of probation will result in a written confirmation of regularisation.
- The Company reserves the right to extend the probationary period by a maximum of **{$d['max_probation_extension_months']} months**.

## 6. Applicable Policies

Your employment is subject to the Company's HR policies and procedures, including but not limited to:

- **Employment Contract** (executed separately) — governs compensation, working hours, and termination terms.
- **Non-Disclosure Agreement** (executed separately) — governs confidentiality obligations.
- **Non-Compete Agreement** (executed separately) — governs post-employment restrictions.
- **Leave Policy** (issued separately) — governs entitlements to annual, sick, and other leave types.
- Company Code of Conduct and any other policies communicated from time to time.

In the event of any inconsistency between this Appointment Letter and the Employment Contract, the Employment Contract shall prevail.

## 7. Compensation

Your compensation package, including base salary, benefits, and bonus eligibility, is detailed in your Employment Contract. Your base remuneration is **{$d['currency']} {$d['base_salary']} per annum**, payable on a **{$d['pay_frequency']}** basis.

## 8. Commencement

Kindly report for duty on **{$d['start_date']}** at **{$d['work_location']}** and contact **{$d['reporting_manager']}** upon arrival. Please carry valid identity proof and all documents as specified in the onboarding checklist.

---

## ACCEPTANCE & SIGNATURE

By signing below, both parties confirm that they have read, understood, and agreed to the terms of this Appointment Letter.

| Party | Name | Signature | Date |
|---|---|---|---|
| Company | {$d['signatory_name']} | ___________________________ | {$d['generated_date']} |
| Employee | {$d['employee_name']} | ___________________________ | {$d['generated_date']} |
MD;

        return [
            'type'            => 'appointment_letter',
            'title'           => 'Appointment Letter — ' . $d['employee_name'],
            'content'         => $content,
            'editable_fields' => [
                'designation', 'department', 'start_date', 'reporting_manager',
                'work_location', 'probation_period_months', 'probation_notice_days',
                'max_probation_extension_months', 'base_salary', 'currency', 'pay_frequency'
            ],
            'version'         => 'v1.0',
            'generated_date'  => $d['generated_date'],
        ];
    }

    // ─── EMPLOYMENT CONTRACT ──────────────────────────────────────────────────────
    private function generateEmploymentContract(array $d): array
    {
        $d['probation_notice_days'] = $d['probation_notice_days'] ?? 15;
        $d['standard_working_hours_per_week'] = $d['standard_working_hours_per_week'] ?? 40;
        $d['working_days_per_week'] = $d['working_days_per_week'] ?? 5;

        $d = array_merge([
            'company_name' => 'Your Company',
            'company_address' => 'Plot 93, Rajendra Park, Sector 105, Gurugram � 122001. Haryana',
            'employee_address' => 'Employee Address',
            'benefits_description' => 'Standard company benefits as per policy',
            'dispute_negotiation_days' => 30,
            'dispute_resolution_mechanism' => 'Binding Arbitration',
            'competitor_1' => 'Competitor A',
            'sector_1' => 'Technology',
            'competitor_2' => 'Competitor B',
            'sector_2' => 'Software',
            'competitor_3' => 'Competitor C',
            'sector_3' => 'IT Services',
            'leave_type_name' => 'Annual Leave',
            'days_per_year' => 20,
            'remarks' => 'Subject to approval',
            'annual_leave_days' => 20,
            'sick_leave_days' => 10,
            'casual_leave_days' => 5,
            'accrual_method' => 'monthly',
            'leave_application_notice_days' => 14,
            'sick_leave_doc_threshold' => 3,
            'max_carry_forward_days' => 5,
            'employee_work_location' => 'Office',
            'max_unpaid_leave_days' => 30,
            'maternity_leave_days' => 12,
            'paternity_leave_days' => 5,
            'bereavement_leave_days' => 3,
            'policy_review_frequency' => 'annually',
            'bonus_structure' => 'As per company policy',
        ], $d);

        $content = <<<MD
# Employment Contract

**{$d['company_name']}**
{$d['company_address']}

**Date:** {$d['generated_date']}

---

This Employment Contract ("Contract") is entered into as of **{$d['generated_date']}** between:

**{$d['company_name']}**, incorporated under the laws of {$d['jurisdiction']} ("**Company**");

**AND**

**{$d['employee_name']}** ("**Employee**"), appointed as **{$d['designation']}** in the **{$d['department']}** department.

---

## 1. Parties

The Company engages the Employee, and the Employee accepts engagement, on the terms and conditions set out in this Contract.

## 2. Term of Employment

2.1 The Employee's employment shall commence on **{$d['start_date']}**.

2.2 This Contract shall continue unless terminated in accordance with the provisions herein.

## 3. Duties & Responsibilities

3.1 The Employee shall perform the duties and responsibilities of **{$d['designation']}** as set out in the Job Description provided separately, and such other duties as may be assigned by the Company from time to time.

3.2 The Employee shall devote their full professional time, attention, and skills to the business of the Company.

3.3 The Employee shall comply with all Company policies, procedures, and codes of conduct.

## 4. Compensation & Benefits

| Component | Details |
|---|---|
| Base Salary | {$d['currency']} {$d['base_salary']} per annum |
| Pay Frequency | {$d['pay_frequency']} |
| Bonus | {$d['bonus_structure']} |
| Benefits | {$d['benefits_description']} |

4.1 The Company reserves the right to revise the Employee's compensation annually at its sole discretion.

4.2 All compensation is subject to applicable statutory deductions (income tax, provident fund, etc.) in accordance with the laws of {$d['jurisdiction']}.

## 5. Working Hours

5.1 Standard working hours are **{$d['standard_working_hours_per_week']} hours per week**, {$d['working_days_per_week']} days per week.

5.2 The Employee may be required to work additional hours based on business requirements without additional compensation unless otherwise required by applicable law.

## 6. Probation Period

6.1 The Employee shall serve a probationary period of **{$d['probation_period_months']} month(s)** from the commencement date.

6.2 During the probationary period, either party may terminate this Contract by giving **{$d['probation_notice_days']} days** written notice.

6.3 Upon satisfactory completion, the Employee's appointment shall be confirmed in writing.

## 7. Termination Conditions

**7.1 Notice Period (Post-Probation)**
Either party may terminate this Contract by providing **{$d['notice_period_days']} days** written notice to the other party. The Company may elect to pay salary in lieu of notice.

**7.2 Immediate Termination by Company (Without Notice)**
The Company may terminate this Contract immediately without notice and without payment in lieu of notice in the event of:
- Gross misconduct or dishonesty.
- Theft, fraud, or wilful damage to Company property.
- Serious breach of the Non-Disclosure Agreement or this Contract.
- Conviction of a criminal offence involving moral turpitude.
- Persistent or wilful neglect of duties.
- Any other act that, in the Company's reasonable judgment, constitutes serious misconduct.

**7.3 Termination by Employee**
The Employee shall give the Company **{$d['notice_period_days']} days** written notice of resignation.

**7.4 Garden Leave**
During any notice period, the Company may place the Employee on garden leave, during which the Employee remains employed and bound by all obligations but may be excluded from Company premises and systems.

## 8. Confidentiality

8.1 The Employee's confidentiality obligations are set out in the Non-Disclosure Agreement ("NDA") executed on **{$d['generated_date']}**, which is incorporated herein by reference.

8.2 The confidentiality obligations shall survive termination of this Contract for a period of **{$d['confidentiality_duration_years']} year(s)**.

## 9. Non-Compete

9.1 The Employee's non-compete and non-solicitation obligations are set out in the Non-Compete Agreement executed on **{$d['generated_date']}**, which is incorporated herein by reference.

9.2 The non-compete obligations shall apply for a period of **{$d['non_compete_duration_months']} month(s)** post-termination within the geographic scope of **{$d['non_compete_geographic_scope']}**.

## 10. Intellectual Property Assignment

10.1 All inventions, discoveries, works of authorship, software, data, processes, methods, improvements, and other intellectual property ("Work Product") created, developed, or contributed to by the Employee during the course of employment — whether during working hours or otherwise — using the Company's resources, information, or as a result of the Employee's employment — shall be the exclusive property of the Company.

10.2 The Employee hereby assigns to the Company all rights, title, and interest in and to all Work Product, and agrees to execute all documents and take all actions reasonably required to vest such rights in the Company.

10.3 This assignment shall survive the termination of this Contract.

## 11. Dispute Resolution

11.1 The parties agree to first attempt to resolve any disputes arising under this Contract through good-faith negotiation.

11.2 If unresolved within **{$d['dispute_negotiation_days']} days**, the dispute shall be referred to {$d['dispute_resolution_mechanism']} in accordance with the rules applicable in {$d['jurisdiction']}.

11.3 Nothing in this clause shall prevent either party from seeking urgent injunctive relief from a competent court.

## 12. Governing Law

This Contract shall be governed by and construed in accordance with the laws of **{$d['jurisdiction']}**. The parties submit to the exclusive jurisdiction of the competent courts of {$d['jurisdiction']}.

## 13. Entire Agreement

This Contract, together with the Appointment Letter, NDA, Non-Compete Agreement, and Leave Policy, constitutes the entire agreement between the parties with respect to the Employee's employment and supersedes all prior negotiations, representations, or agreements, whether oral or written.

---

**SIGNATURES**

| Party | Name | Designation | Signature | Date |
|---|---|---|---|---|
| Company | {$d['signatory_name']} | {$d['signatory_title']} | _______________ | {$d['generated_date']} |
| Employee | {$d['employee_name']} | {$d['designation']} | _______________ | {$d['generated_date']} |

---

*This document is a template generated for internal HR use and should be reviewed by legal counsel for jurisdiction-specific enforceability.*
MD;

        return [
            'type'            => 'employment_contract',
            'title'           => 'Employment Contract — ' . $d['employee_name'],
            'content'         => $content,
            'editable_fields' => [
                'base_salary', 'currency', 'pay_frequency', 'bonus_structure', 'benefits_description',
                'standard_working_hours_per_week', 'working_days_per_week', 'probation_period_months',
                'probation_notice_days', 'notice_period_days', 'confidentiality_duration_years',
                'non_compete_duration_months', 'non_compete_geographic_scope', 'dispute_negotiation_days',
                'dispute_resolution_mechanism', 'jurisdiction', 'start_date'
            ],
            'version'         => 'v1.0',
            'generated_date'  => $d['generated_date'],
        ];
    }

    // ─── NON-COMPETE ─────────────────────────────────────────────────────────────
    private function generateNonCompete(array $d): array
    {
        $d = array_merge([
            'company_name' => 'Your Company',
            'company_address' => 'Plot 93, Rajendra Park, Sector 105, Gurugram � 122001. Haryana',
            'employee_address' => 'Employee Address',
            'benefits_description' => 'Standard company benefits as per policy',
            'dispute_negotiation_days' => 30,
            'dispute_resolution_mechanism' => 'Binding Arbitration',
            'competitor_1' => 'Competitor A',
            'sector_1' => 'Technology',
            'competitor_2' => 'Competitor B',
            'sector_2' => 'Software',
            'competitor_3' => 'Competitor C',
            'sector_3' => 'IT Services',
            'leave_type_name' => 'Annual Leave',
            'days_per_year' => 20,
            'remarks' => 'Subject to approval',
            'annual_leave_days' => 20,
            'sick_leave_days' => 10,
            'casual_leave_days' => 5,
            'accrual_method' => 'monthly',
            'leave_application_notice_days' => 14,
            'sick_leave_doc_threshold' => 3,
            'max_carry_forward_days' => 5,
            'employee_work_location' => 'Office',
            'max_unpaid_leave_days' => 30,
            'maternity_leave_days' => 12,
            'paternity_leave_days' => 5,
            'bereavement_leave_days' => 3,
            'policy_review_frequency' => 'annually',
            'bonus_structure' => 'As per company policy',
        ], $d);
        $content = <<<MD
# Non-Compete Agreement

**{$d['company_name']}**
{$d['company_address']}

**Date:** {$d['generated_date']}

---

This Non-Compete Agreement ("Agreement") is entered into as of **{$d['generated_date']}** between:

**{$d['company_name']}** ("**Company**"); AND **{$d['employee_name']}** ("**Employee**").

---

## 1. Non-Competition Covenant

⚠️ **Admin Review Required:** The duration and geographic scope of this clause are the two fields most likely to require jurisdiction-specific review, as non-compete enforceability varies significantly by region.

During the Employee's employment with the Company and for a period of **{$d['non_compete_duration_months']} month(s)** following the termination of employment (for any reason) ("**Restricted Period**"), the Employee shall not, directly or indirectly:

1.1 Engage in, own, manage, operate, control, be employed by, consult for, participate in, or be connected in any manner with any **Competing Business** (as defined below) within the geographic area of **{$d['non_compete_geographic_scope']}** ("**Restricted Area**").

1.2 Assist any person or entity in establishing or conducting a Competing Business within the Restricted Area.

## 2. Definition of "Competing Business"

"**Competing Business**" means any business, enterprise, or activity that:

- Provides products or services that are the same as, similar to, or that compete with the products or services offered by the Company; OR
- Is engaged in the same or substantially similar industry sector as the Company; AND
- Operates within or targets the Restricted Area.

The Company shall provide the Employee with a list of specific competitors considered Competing Businesses at the time of execution; this list may be updated by written notice. *(See **Schedule A** — Competing Business List)*

## 3. Non-Solicitation of Clients

During the Restricted Period, the Employee shall not, directly or indirectly:

3.1 Solicit, divert, or attempt to solicit or divert any client, customer, or prospective client of the Company with whom the Employee had contact or about whom the Employee received Confidential Information during their employment.

3.2 Induce any such client or customer to reduce, terminate, or materially alter their business relationship with the Company.

## 4. Non-Solicitation of Employees

During the Restricted Period, the Employee shall not, directly or indirectly:

4.1 Solicit, recruit, or attempt to induce any employee or contractor of the Company to terminate their relationship with the Company.

4.2 Hire or engage, directly or indirectly, any person who was an employee or contractor of the Company during the twelve (12) months preceding the Employee's termination.

## 5. Consideration

The Employee acknowledges receiving the following consideration for entering into this Agreement:

- Access to Confidential Information of the Company.
- Specialised training, professional development, and resources provided by the Company.
- Compensation in the amount of **{$d['currency']} {$d['base_salary']} per annum**.
- Access to Company's clients, customer base, and goodwill.

The Employee acknowledges that this consideration is adequate and sufficient to support the obligations contained herein.

## 6. Severability

6.1 If any provision of this Agreement is held invalid, unenforceable, or void by a court of competent jurisdiction, such provision shall be deemed amended to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force and effect.

6.2 The parties authorise any court of competent jurisdiction to modify this Agreement to the extent necessary to make it enforceable in accordance with applicable law.

## 7. Remedies

7.1 The Employee acknowledges that breach of this Agreement would cause the Company irreparable harm for which monetary damages would be inadequate.

7.2 The Company shall be entitled to seek injunctive relief — including temporary restraining orders and preliminary and permanent injunctions — without the necessity of proving actual damages or posting bond.

7.3 The Company shall also be entitled to pursue all other legal and equitable remedies available, including recovery of damages, legal costs, and attorneys' fees.

## 8. Governing Law

This Agreement shall be governed by and construed in accordance with the laws of **{$d['jurisdiction']}**.

---

**SCHEDULE A — Competing Business List**

*(To be completed by Admin/HR at time of execution)*

| # | Competing Business Name | Industry / Sector |
|---|---|---|
| 1 | {$d['competitor_1']} | {$d['sector_1']} |
| 2 | {$d['competitor_2']} | {$d['sector_2']} |
| 3 | {$d['competitor_3']} | {$d['sector_3']} |

---

**SIGNATURES**

| Party | Name | Signature | Date |
|---|---|---|---|
| Company | {$d['signatory_name']} | ___________________________ | {$d['generated_date']} |
| Employee | {$d['employee_name']} | ___________________________ | {$d['generated_date']} |

---

*This document is a template generated for internal HR use and should be reviewed by legal counsel for jurisdiction-specific enforceability.*
MD;

        return [
            'type'            => 'non_compete',
            'title'           => 'Non-Compete Agreement — ' . $d['employee_name'],
            'content'         => $content,
            'editable_fields' => [
                'non_compete_duration_months',    // ⚠️ HIGH PRIORITY — jurisdiction-specific
                'non_compete_geographic_scope',   // ⚠️ HIGH PRIORITY — jurisdiction-specific
                'base_salary', 'currency', 'jurisdiction', 'competitor_1', 'competitor_2', 'competitor_3', 'sector_1', 'sector_2', 'sector_3'
            ],
            'version'         => 'v1.0',
            'generated_date'  => $d['generated_date'],
        ];
    }

    // ─── LEAVE POLICY ────────────────────────────────────────────────────────────
    private function generateLeavePolicy(array $d): array
    {
        // Build leave types table
        $leaveTable = "| Leave Type | Days Per Year | Remarks |\n|---|---|---|\n";
        $remarks = $d['remarks'] ?? '';
        if (!empty($d['leave_types'])) {
            foreach ($d['leave_types'] as $lt) {
                $name = $lt['name'] ?? 'Annual Leave';
                $days = $lt['days'] ?? '20';
                $leaveTable .= "| {$name} | {$days} | {$remarks} |\n";
            }
        } else {
            $annualLeave = $d['annual_leave_days'] ?? '20';
            $sickLeave = $d['sick_leave_days'] ?? '10';
            $casualLeave = $d['casual_leave_days'] ?? '5';
            $leaveTable .= "| Annual Leave | {$annualLeave} | {$remarks} |\n";
            $leaveTable .= "| Sick Leave | {$sickLeave} | Medical certificate required for absences exceeding 2 consecutive days |\n";
            $leaveTable .= "| Casual Leave | {$casualLeave} | Prior approval required |\n";
        }

        $d = array_merge([
            'company_name' => 'Your Company',
            'company_address' => 'Plot 93, Rajendra Park, Sector 105, Gurugram � 122001. Haryana',
            'employee_address' => 'Employee Address',
            'benefits_description' => 'Standard company benefits as per policy',
            'dispute_negotiation_days' => 30,
            'dispute_resolution_mechanism' => 'Binding Arbitration',
            'competitor_1' => 'Competitor A',
            'sector_1' => 'Technology',
            'competitor_2' => 'Competitor B',
            'sector_2' => 'Software',
            'competitor_3' => 'Competitor C',
            'sector_3' => 'IT Services',
            'leave_type_name' => 'Annual Leave',
            'days_per_year' => 20,
            'remarks' => 'Subject to approval',
            'annual_leave_days' => 20,
            'sick_leave_days' => 10,
            'casual_leave_days' => 5,
            'accrual_method' => 'monthly',
            'leave_application_notice_days' => 14,
            'sick_leave_doc_threshold' => 3,
            'max_carry_forward_days' => 5,
            'employee_work_location' => 'Office',
            'max_unpaid_leave_days' => 30,
            'maternity_leave_days' => 12,
            'paternity_leave_days' => 5,
            'bereavement_leave_days' => 3,
            'policy_review_frequency' => 'annually',
            'bonus_structure' => 'As per company policy',
        ], $d);

        $content = <<<MD
# Leave Policy

**{$d['company_name']}**

**Effective Date:** {$d['generated_date']}
**Applicable To:** All employees of {$d['company_name']}

---

## 1. Overview

{$d['company_name']} ("the Company") is committed to supporting the health, wellbeing, and work-life balance of its employees. This Leave Policy sets out the types of leave available to employees, the conditions for availing each leave type, and the procedures for applying for and approving leave.

This policy applies to all full-time, part-time, and contract employees of the Company, subject to their individual Employment Contracts and applicable statutory requirements under the laws of **{$d['jurisdiction']}**.

---

## 2. Leave Types

The following leave entitlements are applicable for each calendar year:

{$leaveTable}

*All leave entitlements are subject to applicable statutory minimums under the laws of {$d['jurisdiction']}. In the event of any inconsistency between this policy and statutory requirements, statutory requirements shall prevail.*

---

## 3. Accrual Rules

3.1 **Accrual Method:** Leave entitlements accrue on a **{$d['accrual_method']}** basis (e.g., monthly, quarterly, annually upfront).

3.2 **Eligibility:** Employees are eligible to avail leave after completing their **{$d['probation_period_months']}-month** probationary period, unless otherwise required by law.

3.3 **Prorated Leave:** Employees joining mid-year shall receive prorated leave entitlements calculated from the date of joining.

3.4 **Minimum Service:** Certain leave types (e.g., annual leave) may require a minimum period of continuous service before they can be availed. Specific requirements are detailed in the Leave Types table above.

---

## 4. Application Process

4.1 **Prior Approval Required:** All planned leave (Annual, Casual, and other foreseeable leave) must be applied for and approved in advance through the Company's HR Management System or by written request to the Reporting Manager.

4.2 **Notice Period for Leave Application:**
- Annual Leave / Planned Leave: Minimum **{$d['leave_application_notice_days']} working days** prior notice.
- Sick Leave: The employee must notify their Reporting Manager as early as possible on the first day of absence, or before commencement of working hours.

4.3 **Supporting Documentation:**
- Sick Leave exceeding **{$d['sick_leave_doc_threshold']} consecutive days** requires a valid medical certificate from a registered medical practitioner.
- Other leave types may require supporting documentation as determined by HR.

4.4 **Approval Authority:** All leave applications are subject to approval by the employee's Reporting Manager and, where applicable, the HR Department. Approval is not automatic and may be declined based on business requirements.

---

## 5. Carry-Forward & Encashment Rules

5.1 **Carry-Forward:** A maximum of **{$d['max_carry_forward_days']} days** of Annual Leave may be carried forward to the next calendar year. Leave in excess of this limit shall lapse at year-end unless otherwise approved in writing by the HR Department.

5.2 **Encashment:** Leave encashment (payment in lieu of unused leave) shall be permitted only upon termination of employment, in accordance with applicable statutory provisions. Encashment during active employment is subject to Company approval and may be offered at the Company's sole discretion.

5.3 **Sick Leave Encashment:** Sick leave is generally not encashable and does not carry forward unless otherwise required by applicable law.

---

## 6. Public Holidays

6.1 In addition to the leave entitlements above, employees are entitled to all statutory and declared public holidays applicable in **{$d['jurisdiction']}** and at the work location of **{$d['employee_work_location']}**.

6.2 The Company shall publish an annual list of applicable public holidays by the start of each calendar year.

6.3 If an employee is required to work on a public holiday, they shall be entitled to compensatory leave or additional remuneration in accordance with applicable law.

---

## 7. Unpaid Leave

7.1 Employees who have exhausted all applicable paid leave entitlements may apply for unpaid leave, subject to the written approval of the HR Department and Reporting Manager.

7.2 Unpaid leave may be granted at the Company's sole discretion based on the employee's service record, business requirements, and the circumstances of the request.

7.3 A single period of unpaid leave shall not normally exceed **{$d['max_unpaid_leave_days']} consecutive days** without specific approval from senior management.

7.4 Extended periods of unauthorized absence may be treated as misconduct and may result in disciplinary action, up to and including termination of employment.

---

## 8. Special Leave

### 8.1 Maternity Leave
Female employees are entitled to maternity leave in accordance with the applicable statutory provisions of **{$d['jurisdiction']}**, for a minimum period of **{$d['maternity_leave_days']} weeks**. Maternity leave is fully paid in accordance with applicable law.

### 8.2 Paternity Leave
Male employees are entitled to **{$d['paternity_leave_days']} days** of paid paternity leave upon the birth or adoption of a child.

### 8.3 Bereavement Leave
Employees are entitled to **{$d['bereavement_leave_days']} days** of paid bereavement leave upon the death of an immediate family member (spouse, child, parent, sibling). Additional bereavement leave may be granted at the Company's discretion.

### 8.4 Other Special Leave
Any other special leave (study leave, marriage leave, adoption leave, etc.) shall be considered on a case-by-case basis by the HR Department, subject to applicable statutory requirements.

---

## 9. Policy Review

This Leave Policy shall be reviewed **{$d['policy_review_frequency']}** by the HR Department and updated as necessary to reflect changes in applicable law, business requirements, or employee feedback.

---

*This policy was issued by {$d['company_name']} HR Department and is effective from {$d['generated_date']}.*
MD;

        return [
            'type'            => 'leave_policy',
            'title'           => 'Leave Policy — ' . $d['company_name'],
            'content'         => $content,
            'editable_fields' => [
                'accrual_method', 'leave_application_notice_days', 'sick_leave_doc_threshold',
                'max_carry_forward_days', 'max_unpaid_leave_days', 'maternity_leave_days',
                'paternity_leave_days', 'bereavement_leave_days', 'policy_review_frequency',
                'employee_work_location', 'jurisdiction', 'probation_period_months'
            ],
            'version'         => 'v1.0',
            'generated_date'  => $d['generated_date'],
        ];
    }
}
