TYPE=VIEW
query=select `ui`.`id` AS `id`,`ui`.`email` AS `email`,`ui`.`password` AS `password`,`ui`.`role_id` AS `role_id`,`ui`.`created_at` AS `joined_at`,coalesce(`sa`.`name`,`ad`.`name`,`em`.`name`,`dev`.`name`,concat(`v`.`first_name`,\' \',`v`.`last_name`)) AS `name`,coalesce(`sa`.`employee_id`,`ad`.`employee_id`,`em`.`employee_id`,`dev`.`employee_id`,`v`.`vendor_id`) AS `employee_id`,`v`.`vendor_id` AS `vendor_id`,coalesce(`sa`.`status`,`ad`.`status`,`em`.`status`,`dev`.`status`,`v`.`status`) AS `status`,`em`.`department_id` AS `department_id`,coalesce(`sa`.`phone`,`v`.`phone`) AS `phone`,coalesce(`sa`.`company_name`,`ad`.`company_name`,`em`.`company_name`,`dev`.`company_name`,`v`.`company_name`) AS `company_name` from (((((`management_system`.`user_identities` `ui` left join `management_system`.`superadmins` `sa` on(`ui`.`id` = `sa`.`user_id`)) left join `management_system`.`admins` `ad` on(`ui`.`id` = `ad`.`user_id`)) left join `management_system`.`employees` `em` on(`ui`.`id` = `em`.`user_id`)) left join `management_system`.`developers` `dev` on(`ui`.`id` = `dev`.`user_id`)) left join `management_system`.`vendors` `v` on(`ui`.`id` = `v`.`user_id`))
md5=5402ee8cfd9cff846eab73a0cd3e2436
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001784802326938090
create-version=2
source=SELECT \n        ui.id AS id, \n        ui.email AS email, \n        ui.password AS password, \n        ui.role_id AS role_id, \n        ui.created_at AS joined_at, \n        COALESCE(sa.name, ad.name, em.name, dev.name, CONCAT(v.first_name, \' \', v.last_name)) AS name, \n        COALESCE(sa.employee_id, ad.employee_id, em.employee_id, dev.employee_id, v.vendor_id) AS employee_id, \n        v.vendor_id AS vendor_id, \n        COALESCE(sa.status, ad.status, em.status, dev.status, v.status) AS status, \n        em.department_id AS department_id, \n        COALESCE(sa.phone, v.phone) AS phone, \n        COALESCE(sa.company_name, ad.company_name, em.company_name, dev.company_name, v.company_name) AS company_name \n      FROM user_identities ui \n      LEFT JOIN superadmins sa ON ui.id = sa.user_id \n      LEFT JOIN admins ad ON ui.id = ad.user_id \n      LEFT JOIN employees em ON ui.id = em.user_id \n      LEFT JOIN developers dev ON ui.id = dev.user_id \n      LEFT JOIN vendors v ON ui.id = v.user_id
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `ui`.`id` AS `id`,`ui`.`email` AS `email`,`ui`.`password` AS `password`,`ui`.`role_id` AS `role_id`,`ui`.`created_at` AS `joined_at`,coalesce(`sa`.`name`,`ad`.`name`,`em`.`name`,`dev`.`name`,concat(`v`.`first_name`,\' \',`v`.`last_name`)) AS `name`,coalesce(`sa`.`employee_id`,`ad`.`employee_id`,`em`.`employee_id`,`dev`.`employee_id`,`v`.`vendor_id`) AS `employee_id`,`v`.`vendor_id` AS `vendor_id`,coalesce(`sa`.`status`,`ad`.`status`,`em`.`status`,`dev`.`status`,`v`.`status`) AS `status`,`em`.`department_id` AS `department_id`,coalesce(`sa`.`phone`,`v`.`phone`) AS `phone`,coalesce(`sa`.`company_name`,`ad`.`company_name`,`em`.`company_name`,`dev`.`company_name`,`v`.`company_name`) AS `company_name` from (((((`management_system`.`user_identities` `ui` left join `management_system`.`superadmins` `sa` on(`ui`.`id` = `sa`.`user_id`)) left join `management_system`.`admins` `ad` on(`ui`.`id` = `ad`.`user_id`)) left join `management_system`.`employees` `em` on(`ui`.`id` = `em`.`user_id`)) left join `management_system`.`developers` `dev` on(`ui`.`id` = `dev`.`user_id`)) left join `management_system`.`vendors` `v` on(`ui`.`id` = `v`.`user_id`))
mariadb-version=101108
