name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # If the folder exists but isn't a git repository, back it up so we can clone freshly
            if [ -d "/var/www/react-erp" ] && [ ! -d "/var/www/react-erp/.git" ]; then
              mv /var/www/react-erp /var/www/react-erp_backup_$(date +%s)
            fi

            # Navigate to the deployment directory or clone it if it doesn't exist
            if [ ! -d "/var/www/react-erp" ]; then
              mkdir -p /var/www
              cd /var/www
              git clone https://${{ secrets.GIT_PAT }}@github.com/Avnish06/react-erp.git
            fi
            
            cd /var/www/react-erp
            git pull origin main
            
            # Install Backend Dependencies & Restart
            cd server
            npm install
            pm2 delete react-erp || true
            pm2 delete react-erp-backend || true
            pm2 start index.js --name "react-erp"
            pm2 save
            
            # Install Frontend Dependencies & Build
            cd ../Webfrontend
            npm install
            npm run build
